CREATE TABLE IF NOT EXISTS Usuario (
                                       id    VARCHAR(10)  NOT NULL,
    clave VARCHAR(100) NOT NULL,
    rol   VARCHAR(10)  NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS Tipo (
                                    id     VARCHAR(10) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS Documento (
                                         id          VARCHAR(10) NOT NULL,
    descripcion VARCHAR(50) NOT NULL,
    monto       FLOAT,
    timbres     FLOAT,
    tipo        VARCHAR(10),
    PRIMARY KEY (id),
    FOREIGN KEY (tipo) REFERENCES Tipo(id)
    );

CREATE TABLE IF NOT EXISTS Linea (
                                     id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     usuario   VARCHAR(10) NOT NULL,
    documento VARCHAR(10) NOT NULL,
    cantidad  INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (usuario)   REFERENCES Usuario(id),
    FOREIGN KEY (documento) REFERENCES Documento(id)
    );